### ISSUE TITLE
[Q] f_open error on Github-version from 27.09.2023?

### ISSUE THREAD

**Issue by guidol70** [Isysxp/Pico_1140#9]
Dear Ian,
it seems that I havent compiled Pico1140 since 1 year :(
The last chances on github are from the 27.09.2023 - so I would also compile a "final" release :)

So I updated my Pico-SDK, put the new github-files in my Directory and did compile.
Compile went fine without errors.

The Pico-1140 does startup and I can enter my Boot-devices, but then I get a f_open error for my boot-device :( no matter which file I choose and no difference between RK or RL.
ONLY on RL-Boot the filenames does show up which it doesnt on RK-Boot :(

Do you got an idea what went wrong? The SDCard and Bootfiles did work with the verson from last year.

Is there a change in the needed filenames or could this be an error with the Pico-SDK-Update?

Kind regards
Guido

![Pico1140_fopen_error](https://github.com/Isysxp/Pico_1140/assets/5121124/d75ffb16-783b-4c58-a83a-7ea8b12a8e02)

**Comment by guidol70** [comment]
`

        printf("\nDEBUG - RK-File: >%s<\r\n", rkfile);
        printf("\nDEBUG - RL-File: >%s<\r\n", rlfile);
        startup(rkfile,rlfile,bootdev);

DEBUG - RK-File: ><
DEBUG - RL-File: >rt1157.rl02<
f_open() error: The path name format is invalid (6)


`


RL-Boot (with filename)

![Pico1140_fopen_error_RL](https://github.com/Isysxp/Pico_1140/assets/5121124/258e93cf-7aad-4ae8-b44a-752112f80fe1)

**Comment by Isysxp** [comment]
Hi Guido,

 This is due to the fact that the app can use either a USB com port or a hardware serial port (pins 14/15 on Sparkfun board).
 If the RX pin (14) is left unconnected, this can result in garbage data being received by the UART. 
 I have patched Pico_1140.cxx with a weak pull up for the UART RX pin when it it not connected. I hope this sorts the problem out.

BW, Ian.

**Comment by guidol70** [comment]
> This is due to the fact that the app can use either a USB com port or a hardware serial port
If the RX pin (14) is left unconnected, this can result in garbage data being received by the UART. 
I have patched Pico_1140.cxx with a weak pull up for the UART RX pin when it it not connected. 
I hope this sorts the problem out.

Hi Ian,
Great - thats was a fast fix and yes you sorted it out.
Now my compiled version of Pico-1140 does boot again.
I had never thought at the serial port, when I do get a filename-error ;)

I did set my USB port to 115200, but it istn much faster than the 9600...
Didnt I ask this in the last year also?

Many Thanks for the fast fix :)

Kind regards
Guido

![Pico1140_fopen_error_FIXED](https://github.com/Isysxp/Pico_1140/assets/5121124/5147d511-16aa-4e6f-8efd-64edb2b4be42)

**Comment by Isysxp** [comment]
Hi Guido,

 No problem. The character rate is determined by the TT: poll rate in avr11.cxx line 162.
 This is set to 2000 instruction cycles which can be reduced. This is based on my guess for an 11/40 running at 2 MIPS.
 The poll rate is equivalent to 1KHz which matches the throughput of a 9600 Baud serial link. You could reduce this number but it may cause some problems with some operating systems.....

Regards, Ian.
